name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - bin/**
      - lib/**
      - .github/workflows/deploy.yml
      - .github/actions/setup-node-npm/**

concurrency:
  group: deploy
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  management:
    runs-on: ubuntu-slim
    environment: management
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ./.github/actions/setup-node-npm
      - uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ vars.AWS_MANAGEMENT_DEPLOY_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Deploy ManagementGithubDeployRoleStack
        run: npx cdk deploy ManagementGithubDeployRoleStack --require-approval never
        env:
          AWS_MANAGEMENT_ACCOUNT_ID: ${{ vars.AWS_MANAGEMENT_ACCOUNT_ID }}
          APEX_DOMAIN_NAME: ${{ vars.APEX_DOMAIN_NAME }}
          BLOG_SUBDOMAIN_NAME_SERVERS: ${{ vars.BLOG_SUBDOMAIN_NAME_SERVERS }}
          GOOGLE_SITE_VERIFICATION_TOKEN: ${{ vars.GOOGLE_SITE_VERIFICATION_TOKEN }}
          APEX_LANDING_CLOUDFRONT_DOMAIN_NAME: ${{ vars.APEX_LANDING_CLOUDFRONT_DOMAIN_NAME }}
          APEX_LANDING_CERT_VALIDATION_RECORD_NAME: ${{ vars.APEX_LANDING_CERT_VALIDATION_RECORD_NAME }}
          APEX_LANDING_CERT_VALIDATION_RECORD_VALUE: ${{ vars.APEX_LANDING_CERT_VALIDATION_RECORD_VALUE }}
      - name: Deploy platform stacks
        run: >-
          npx cdk deploy
          DnsStack
          --require-approval never
        env:
          AWS_MANAGEMENT_ACCOUNT_ID: ${{ vars.AWS_MANAGEMENT_ACCOUNT_ID }}
          APEX_DOMAIN_NAME: ${{ vars.APEX_DOMAIN_NAME }}
          BLOG_SUBDOMAIN_NAME_SERVERS: ${{ vars.BLOG_SUBDOMAIN_NAME_SERVERS }}
          GOOGLE_SITE_VERIFICATION_TOKEN: ${{ vars.GOOGLE_SITE_VERIFICATION_TOKEN }}
          APEX_LANDING_CLOUDFRONT_DOMAIN_NAME: ${{ vars.APEX_LANDING_CLOUDFRONT_DOMAIN_NAME }}
          APEX_LANDING_CERT_VALIDATION_RECORD_NAME: ${{ vars.APEX_LANDING_CERT_VALIDATION_RECORD_NAME }}
          APEX_LANDING_CERT_VALIDATION_RECORD_VALUE: ${{ vars.APEX_LANDING_CERT_VALIDATION_RECORD_VALUE }}
